backend:
  name: git-gateway
  accept_roles:
    - admin

public_folder: "/assets"
media_folder: ".vuepress/public/assets"
display_url: http://vegarevolutionmusic.com/

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "README.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Parallax Image", name: "parallaxImage", widget: "file"}
          - {label: "Parallax Header", name: "parallaxHeader", widget: "string"}
          - {label: "Parallax Content", name: "parallaxContent", widget: "text", required: false}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Bio"
        name: "bio"
        file: "bio.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "List of Works"
        name: "list"
        file: "list.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Contact"
        name: "contact"
        file: "contact.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string", required: false}
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "sample"
    label: "Samples"
    folder: "sample"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "works"
    label: "Works"
    folder: "works"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Type", name: "workType", widget: "select", options: ["", "audio", "video", "youtube"]}
      - {label: "File", name: "file", widget: "file", required: false}
      - {label: "ID", name: "id", widget: "string", required: false}
      - {label: "Is a Playlist", name: "playlist", widget: "boolean", required: false}
      - {label: "Embed Code", name: "raw", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "events"
    label: "Events"
    folder: "events"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Event Url", name: "url", widget: "string", required: false}
      - {label: "Group", name: "group", widget: "string", required: false}
      - {label: "Group Url", name: "groupUrl", widget: "string", required: false}
      - {label: "Venue", name: "venue", widget: "string", required: false}
      - {label: "Venue Url", name: "venueUrl", widget: "string", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Date and Time", name: "datetime", widget: "datetime", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
